#!/bin/sh

COMMAND="$1"

if [ "$COMMAND" = "" ]; then
    echo "Command missing."
    exit 1
fi

THIS_PATH=`readlink -f "$0"`
BIN_PATH=`dirname "$THIS_PATH"`
BASE_PATH=`dirname "$BIN_PATH"`

SRC_PATH="$BASE_PATH/src"
REPO_PATH="$BASE_PATH/debian"
BUILD_PATH="$BASE_PATH/build"

S3_BUCKET="s3://packages.xd.fi"
DISTRIBUTIONS=`cat "$BASE_PATH/conf/distributions" |grep "Codename:" |cut -d" " -f2`

SYNC_TO_S3="$REPO_PATH $BASE_PATH/index.html $BASE_PATH/install.sh"

case $COMMAND in
    add)
        PACKAGE="$2"
        if [ -f "$PACKAGE" ]; then
            for d in $DISTRIBUTIONS ; do
                PKG=`basename "$PACKAGE"`
                echo "Adding: $PKG"
                reprepro -b $BASE_PATH --outdir $REPO_PATH includedeb "$d" "$PACKAGE" >/dev/null
            done
        else
            echo "File not found: $PACKAGE"
            exit 1
        fi
        ;;
    add_all)
        for f in $BUILD_PATH/*.deb ; do
            $0 add "$f"
        done
        ;;
    build)
        SRC="$2"
        FULL_PATH=`readlink -f "$SRC"`

        if [ ! -d "$BUILD_PATH" ]; then
            mkdir -p $BUILD_PATH
        fi
        cd $BUILD_PATH

        if [ -f "$FULL_PATH" ]; then
            PKG=`basename "$FULL_PATH" |cut -d. -f1`
            echo "Building: $PKG"
            equivs-build "$FULL_PATH" >/dev/null
        else
            echo "File not found: $FULL_PATH"
            exit 1
        fi
        ;;
    build_all)
        for f in $SRC_PATH/*.control ; do
            $0 build "$f"
        done
        ;;
    sync)
        for f in $SYNC_TO_S3 ; do
            s3cmd sync "$f" $S3_BUCKET
        done
        ;;
    update)
        $0 build_all
        $0 add_all
        $0 sync
        ;;
    install-requirements)
        apt-get install equivs s3cmd reprepro
        ;;
    **)
        echo "Unknown command $COMMAND"
        ;;
esac
